<?php
/**
 * Author: Joris Rietveld <jorisrietveld@gmail.com>
 * Created: 31-05-2017 21:23
 * Licence: GNU General Public licence version 3 <https://www.gnu.org/licenses/quick-guide-gplv3.html>
 */
declare(strict_types=1);

namespace RestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity
 * @ORM\Table(name="ClientPot")
 * @Gedmo\SoftDeleteable(fieldName="dateRemoved", timeAware=false)
 */
class ClientPot
{
    /**
     * This column holds the unique record identification code that is generated by the database upon record creation.
     *
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * This column holds an reference to the unique identifier of the client entity.
     * @var int
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     * @ORM\OneToMany(targetEntity="RestBundle\Entity\Client")
     */
    protected $client;

    /**
     * This column holds an reference to the unique identifier of the pot entity.
     * @var int
     * @ORM\JoinColumn(name="pot_id", referencedColumnName="id")
     * @ORM\OneToMany(targetEntity="RestBundle\Entity\Pot")
     */
    protected $pot;

    /**
     * This column holds the date the client was coupled to an plant pot.
     * @var DateTime
     * @ORM\Column(name="couple_date", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    protected $coupleDate;

    /**
     * This column holds the timestamp of the date the record was soft deleted. The record will still exist in the
     * database but marked as unactive.
     *
     * @var \DateTime
     * @ORM\Column(name="date_removed", type="datetime", nullable=true)
     */
    protected $dateRemoved;
}
