<?php
/**
 * Author: Joris Rietveld <jorisrietveld@gmail.com>
 * Created: 31-05-2017 21:23
 * Licence: GNU General Public licence version 3 <https://www.gnu.org/licenses/quick-guide-gplv3.html>
 */
declare(strict_types=1);

namespace RestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="ClientPot")
 * @Gedmo\SoftDeleteable(fieldName="dateRemoved", timeAware=false)
 */
class ClientPot
{
    /**
     * This column holds the unique record identification code that is generated by the database upon record creation.
     *
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     *
     * @var
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     * @ORM\OneToMany(targetEntity="RestBundle\Entity\Client")
     */
    protected $client;
    protected $pot;
    protected $coupleDate;
    protected $dateRemoved;
}