<?php
/**
 * Author: Joris Rietveld <jorisrietveld@gmail.com>
 * Created: 31-05-2017 21:19
 * Licence: GNU General Public licence version 3 <https://www.gnu.org/licenses/quick-guide-gplv3.html>
 */
declare(strict_types=1);

namespace RestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="Pot")
 * @Gedmo\SoftDeleteable(fieldName="dateRemoved", timeAware=false)
 */
class Pot implements UserInterface, \Serializable
{
    /**
     * This column holds the unique record identification code that is generated by the database upon record creation.
     *
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * This attribute holds the unique manufacture a code of the network chip in the plant pot.
     *
     * @var string
     * @ORM\Column(type="string", name="pot_mac_address", length=17 )
     */
    protected $potMacAddress;

    /**
     * This atribute holds an hash of the uniquely generated code that is generated for each pot.
     *
     * @var string
     * @ORM\Column(type="string", name="pot_unique_hash", length=255)
     */
    protected $potUniqueHash;

    /**
     * This attribute temporarly stores the uniquely generated code that is generated for each pot
     * to compare it with the hash stored in the database.
     *
     * @var string
     */
    protected $plainPassword;

    /**
     * This attribute holds the pot's manufacture date. That is the date the pot was registered in the
     * database after manufacturing.
     *
     * @var \DateTime
     * @ORM\Column(type="datetime", name="registration_date")
     * @Gedmo\Timestampable(on="create")
     */
    protected $registrationDate;

    /**
     * This attribute holds the date of the first use of the pot (when the app calls the API and tries to authenticate
     * with the pot's mac address and unieque generated code.
     *
     * @var \DateTime
     * @ORM\Column(type="datetime", name="activation_date", nullable=true )
     */
    protected $activationDate;

    /**
     * This column holds the timestamp of the date the record was soft deleted. The record will still exist in the
     * database but marked as unactive.
     *
     * @var \DateTime
     * @ORM\Column(name="date_removed", type="datetime", nullable=true)
     */
    protected $dateRemoved;

    /**
     * This attribute holds the password encoder that will be used for encoding (hashing) the
     * uniquely generated code that is generated for each pot.
     *
     * @var PasswordEncoderInterface
     */
    protected $passwordEncoder;

    /**
     * Returns the roles granted to the user.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Returns the password (secret pot hash) used to authenticate the client.
     *
     * @return string The password
     */
    public function getPassword()
    {
        return $this->potUniqueHash;
    }

    /**
     * This method returns null because
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->potMacAddress;
    }

    public function getMacAddress()
    {
        return $this->getUsername();
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    /**
     * Implemented from the \Serializable interface. It serializes the non sensetive attributes of
     * this entity.
     *
     * @return string
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->potMacAddress,
            $this->potUniqueHash,
            $this->registrationDate,
            $this->activationDate,
            $this->dateRemoved,
        ]);
    }

    /**
     * Implemented from the \Serializable interface. It deserializes entity string to an Pot entity object.
     *
     * @param string $serialized
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->potMacAddress,
            $this->potUniqueHash,
            $this->registrationDate,
            $this->activationDate,
            $this->dateRemoved,
            ) = unserialize($serialized, __CLASS__ );
    }


}