<?php
/**
 * Author: Joris Rietveld <jorisrietveld@gmail.com>
 * Created: 31-05-2017 09:22
 * Licence: GNU General Public licence version 3 <https://www.gnu.org/licenses/quick-guide-gplv3.html>
 */
declare(strict_types=1);

namespace StendenINF1I\WaterupRestApiBundle\Entity;

use Doctrine\Common\Annotations\Annotation\Required;
use Doctrine\ORM\Mapping as ORM;
use FOS\OAuthServerBundle\Entity\Client as BaseClient;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity
 * @ORM\Table(name="Client")
 * @Gedmo\SoftDeleteable(fieldName="dateRemoved", timeAware=false)
 */
class Client extends BaseClient
{
    /**
     * This column holds the unique record identification code that is generated by the database upon record creation.
     *
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * This column holds the device's Universally Unique Identifier that can be used for uniquely identifying
     * the clients mobile device.
     *
     * @var string
     * @ORM\Column(name="uuid", type="string", unique=TRUE, length=255)
     * @Required
     */
    protected $UUID;

    /**
     * This method gets the UUID property.
     *
     * @return string
     */
    public function getUUID()
    {
        return $this->UUID;
    }

    /**
     * This method sets the UUID property.
     *
     * @param string $UUID
     */
    public function setUUID($UUID)
    {
        $this->UUID = $UUID;
    }
}