rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /

app_web:
    resource: "@RestBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@RestBundle/Controller/Api"
    type: annotation