stenden_inf1_i_waterup_rest_api:
    resource: "@StendenINF1IWaterupRestApiBundle/Resources/config/routing.xml"
    prefix: /

greeting:
    type:     rest
    resource: StendenINF1I\WaterupRestApiBundle\Controller\GreetingController