security:
    encoders:
        RestBundle\Entity\Pot:
            algorithm: bcrypt

    providers:
        #plant_pot_provider:
        #    entiry:
        #        class: RestBundle:Pot
        #        property: username
         in_memory:
                    memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
