security:
    encoders:
        RestBundle\Entity\Pot:
            algorithm: bcrypt

    providers:
        plant_pot_provider:
            entiry:
                class: RestBundle:Pot
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
